# ---- Base Node Image ----
FROM node:18-alpine

WORKDIR /admin_panel

# ---- Install & Build React App ----
COPY admin_panel/package.json ./
COPY admin_panel/src ./src
RUN npm install && npm run build

# ---- Serve with NGINX ----
FROM nginx:alpine
COPY --from=0 /admin_panel/build /usr/share/nginx/html
COPY docker/admin.nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]